### ISSUE TITLE
servlet_sec_secform_web.xml contains a wrong url-pattern

### ISSUE THREAD

**Issue by olamy** [eclipse-ee4j/jakartaee-tck#110]
This is preventing starting the webapp.
https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/servlet/spec/security/secform/servlet_sec_secform_web.xml#L348
```
  <servlet-mapping>
    <servlet-name>OneTestServletLogicalName</servlet-name>
    <url-pattern>/On*</url-pattern>
  </servlet-mapping>

```
`/On*` is not correct regarding to specs.

**Comment by olamy** [comment]
simply deploy the war ` servlet_sec_secform_web.war ` in jetty and you will get 
```
java.lang.IllegalArgumentException: Servlet Spec 12.2 violation: suffix glob '*' can only exist after '/': bad spec "/On*"
	at org.eclipse.jetty.http.pathmap.ServletPathSpec.assertValidServletPathSpec(ServletPathSpec.java:136)
	at org.eclipse.jetty.http.pathmap.ServletPathSpec.<init>(ServletPathSpec.java:46)
```

**Comment by RohitKumarJain** [comment]
let me check for the same and will get back to you.

**Comment by markt-asf** [comment]
The mapping `/On*` is specification compliant. It falls under the "All other strings are used for exact matches only". I am not aware of any specification based justification for rejecting such a mapping.

I agree it looks suspect. It is unlikely such a mapping would be defined in web.xml intending it to be an exact match. Tomcat [logs a message](https://github.com/apache/tomcat/blob/master/java/org/apache/catalina/core/StandardContext.java#L6134) in such circumstances since it is possible, but rather unlikely, that the exact match pattern is what was intended.

**Comment by RohitKumarJain** [comment]
When we deploy in Jetty it is expected behavior. (Handling these scenarios may vary by app server to app server selection for deployment), 
(https://eclipse.googlesource.com/jetty/org.eclipse.jetty.project/+/master/jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/ServletPathSpec.java#116)

So if we need mapping like /On*, either redesign this to /One/* so each resource will be a subpath, or apply multiple patterns to one web resource collection like /OnA, /OnB, /OnC so on so forth.

As per investigation below are allowed patterns for Jetty by specification:

1): Path mapping, starting with / and ending with /*
2): Extension mapping, starting with *. (this pattern identifies any resource with given extension ex: *.jsp, *.jpeg, *.csv etc).
3): Default servlet-mapping, containing only / This pattern identifies the default servlet of the application.

**Comment by markt-asf** [comment]
I don't see any text in the Servlet spec that allows a container to reject a url pattern of `/On*` as invalid (as much as I think any such configuration is likely to behave differently than the user expects).

This issue should be resolved as invalid and an issue opened against Jetty.

**Comment by arjantijms** [comment]
@RohitKumarJain the idea is that "/On*" is just a string, and thus is exact mapped. The "*" has no special meaning here. It's treated just like a mapping on "/Ono" or "/Ona" or what have you.
