### ISSUE TITLE
Update configuration settings for GlassFish 6.0 configuration

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#239]
Update create.jacc.vm.options in bin/xml/impl/glassfish/common.xml, as the following is wrong, as [per](https://github.com/eclipse-ee4j/jakartaee-tck/pull/237#discussion_r420575898):
`<param name="jvm.options" value=" -Djakarta.security.jacc.policy.provider=com.sun.ts.tests.jacc.provider.TSPolicy"/>
`

**Comment by alwin-joseph** [comment]
If I am right, the new glassfish with jakarta changes will accept the new property jakarta.security.jacc.policy.provider. Hence the change in jakartaee-tck repo to use jakarta is the right thing. I mentioned this since as of now I see jakartaee-tck build failure due to issue with wrong property name used, as we are not using the latest glassfish. 

Also I hear that latest glassfish build has been successful with jakarta changes.  Hopefully we can use latest bundle to build the tck soon.
