### ISSUE TITLE
Typo and wrong test  in servlet tck

### ISSUE THREAD

**Issue by olamy** [eclipse-ee4j/jakartaee-tck#254]
There is a typo here https://github.com/eclipse-ee4j/jakartaee-tck/blob/a50bf877a5413b812fad569d116c38160ba0aa41/src/com/sun/ts/tests/servlet/spec/errorpage/SecondServletErrorPage.java#L40 `javax.serlvet.error.exception_type` rather than `javax.servlet.error.exception_type` so the test assert the value is null which is wrong because it should contains the class name of the exception. Test here: https://github.com/eclipse-ee4j/jakartaee-tck/blob/a50bf877a5413b812fad569d116c38160ba0aa41/src/com/sun/ts/tests/servlet/spec/errorpage/URLClient.java#L149

**Comment by scottmarlow** [comment]
In summary, the impacted test is currently ignored in all 8.0.x releases of the Jakarta EE Platform TCK, which hides a problem that @olamy is reporting via this issue.  @olamy will submit a pull request that corrects the typo, so that the test will actually run.  @olamy still needs to explain why the test (after typo is corrected) is not Servlet SPEC compliant and what the correction will be (perhaps via pull request).

Sound right @olamy ?

**Comment by olamy** [comment]
@scottmarlow did you look at the PR #277 ?

**Comment by scottmarlow** [comment]
@olamy does [PR#277](https://github.com/eclipse-ee4j/jakartaee-tck/pull/277) address the test failure as well?  Or does it only allow the test failure to occur?

**Comment by olamy** [comment]
#277 is fixing the TCK. This means fixing the servlet request attribute name typo and so fix the corresponding assert/test

**Comment by scottmarlow** [comment]
@olamy I thought that you said before that the test would fail after correcting the typo.  Ah, I see, so it is removing the "null" from what we are testing for.  Previously, the null, masked the fact that there is a typo "javax.serlvet.error.exception_type". :)

**Comment by scottmarlow** [comment]
Closing as I think this is resolved now.  Please reopen if not.
