### ISSUE TITLE
Test failures in webservices12/specialcases

### ISSUE THREAD

**Issue by bhatpmk** [eclipse-ee4j/jakartaee-tck#29]
The JakartaEE TCK run has 9 failures in from the suite webservices12/specialcases/clients/j2w/doclit, as the test fails to find the archives to deploy. 

These tests have prebuilt endpoints, where the clients are built after deploying the endpoints to the serve. The test validates that importing a WSDL from a predeployed webservice endpoint works properly.

**Comment by anajosep** [comment]
Due to a logical error in the run script (docker/run_jakartaeetck.sh), the system property `-Dkeywords` was set as empty, causing the deployment to be skipped when the target `build.special.webservices.clients` were run. This caused the failures in these run. I have corrected the run script accordingly as part of commit id https://github.com/eclipse-ee4j/jakartaee-tck/commit/8b3dc80da58c73ea74cd7eb4fa9779c50e3cebed
