### ISSUE TITLE
Review and promote Jakarta Pages 3.0.0 TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#430]
1.  Complete userguide/documentation changes for Jakarta Pages 3.0.0 TCK.
2.  Review the jakarta-pages-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or pages-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-pages-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
4.  Remove the boolean parameter (PAGES_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/525 is merged which corrects version numbers for tools:
- DOM
- Apache Commons HTTP Client
- Apache Commons Logging
- Apache Commons Codec
 
Would the JSP team like us to stage an updated Jakarta Server Pages TCK with the updated (tool versions corrected) DOC changes?

**Comment by scottmarlow** [comment]
I'm started the build of the JSP TCK via https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master/105/

**Comment by scottmarlow** [comment]
@pnicolucci https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1123/testReport/ shows the JSP tests passed!  

http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/pages-tck-3.0.0.zip contains the staged TCK.  Also worth looking at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/pages-tck-3.0.0-tckinfo.txt to see the updated SHA for the pages-tck-3.0.0.zip.  The updated contents of pages-tck-3.0.0-tckinfo.txt is:
```
***********************************************************************************
***                        TCK bundle information                               ***
*** Name:       pages-tck-3.0.0.zip                                     ***
*** Bundle Copied to URL:    http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/pages-tck-3.0.0.zip ***
*** Date and size: date: 2020-10-15 18:38:27.000000000 +0000, size(b): 11909293        ***
*** SHA256SUM: 2f87385e371f133dec8ab98832169520401704ea885fd81eda8ffca2fac36207 ***
***                                                                             ***
***********************************************************************************
```

Please do let us know when your ready for us to copy the pages-tck-3.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted

CC @kwsutter @kazumura

**Comment by scottmarlow** [comment]
@pnicolucci note that in a few minutes the staged tck will be generated on https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900 which can be reviewed and tested instead of the [jakartaee9/nightly/pages-tck-3.0.0.zip](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/pages-tck-3.0.0.zip).

Thanks @alwin-joseph for catching that and running https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/88 instead!

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1135/testReport/ tests passed!  

http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-pages-tck-3.0.0.zip can now be used

**Comment by scottmarlow** [comment]
Thanks @edbratt for running https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-certification/114/testReport with https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-RC1.zip against http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-pages-tck-3.0.0.zip.  

I talked to @kwsutter about promoting the JSP TCK now and will do so.

**Comment by scottmarlow** [comment]
I removed the boolean parameter (PAGES_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-pages-tck-3.0.0.zip is the promoted JSP TCK (SHA256SUM: 2c90e6896d8321b82521a84746d6db5ee900af31b7850869b890dfde08fee8af is unchanged).

I'm closing this issue, please reopen if we need to promote a different JSP TCK.
