### ISSUE TITLE
Restage authentication TCK

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tck#541]
Following the changes of https://github.com/eclipse-ee4j/jakartaee-tck/pull/540, can the authentication TCK be re-staged?

(btw, which job is normally used for that?)

cc @jeanouii

**Comment by arjantijms** [comment]
I found the job myself. It's https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/

Restaging now via https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/87/

**Comment by scottmarlow** [comment]
Pasting some steps from other stage + promote issue trackers, we missed creating one for Authentication, sorry about that.  

- [ ] 1.  Complete userguide/documentation changes for Jakarta Authentication 2.0.0 TCK.
- [ ] 2.  Review the jakarta-authentication-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
- [ ] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-authentication-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
- [ ] 4.  Remove the boolean parameter (AUTHENTICATION_TCK and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by scottmarlow** [comment]
CC @alwin-joseph

**Comment by arjantijms** [comment]
TCK has been re-staged and is re-executed via https://ci.eclipse.org/authentication/job/2_authentication_run_tck_against_staged_build/26/

**Comment by arjantijms** [comment]
Authentication TCK promoted: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-authentication-tck-2.0.0.zip

**Comment by arjantijms** [comment]
I think we can close this now as all steps have been performed.
