### ISSUE TITLE
JAX-RS: Provider class identity check should be instanceof check

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jakartaee-tck#587]
The test in https://github.com/eclipse-ee4j/jakartaee-tck/blob/c40a006ac3c4d393eb2b5e8ca8d2244847d521fe/src/com/sun/ts/tests/jaxrs/ee/rs/ext/providers/ProvidersServlet.java#L103 checks that the `AnyExceptionExceptionMapper` provider class is properly registered and that the `Providers` implementation returns an instance of that exception mapper provider class.  The intent of the test is good, but the implementation checks whether the provider class returned from `Providers` is the exact same class as the one registered.  

This doesn't work in cases where CDI is used. Section 11.2.3 of the spec says:
> In a product that supports CDI, implementations MUST support the use of CDI-style Beans as root resource classes, providers and Application subclasses. Providers and Application subclasses MUST be singletons or use application scope.

Most CDI-style beans (and particularly application scoped beans) would return a proxy of the actual implementing class, which would fail an `==` check but would pass an `instanceof` check.  I suggest that the TCK test case be modified to:
```
if (em != null && AnyExceptionExceptionMapper.class.isInstance(em))
```

I'll submit a PR with this proposed change shortly.

**Comment by scottmarlow** [comment]
@andymc12 is this a TCK challenge for resolving a TCK failure that an implementation is getting?  Or is this simply intended to be a test improvement?
Santiago Pericas-Geertsen
CC @spericas

**Comment by andymc12** [comment]
@scottmarlow it's basically a "pre-challenge". We are seeing this as a failure when running the RESTful WS 3.0 TCK (CTS?) with Open Liberty using RESTEasy+Weld. @brideck or I will most likely be opening an official challenge, but since it was a fairly easy fix, I thought I would start with it here.  Thanks!

**Comment by scottmarlow** [comment]
@spericas do you agree with addressing this issue for the next EE release (should be EE 9.1)?  Please also review https://github.com/eclipse-ee4j/jakartaee-tck/pull/588 and approve that change.  Thanks!

**Comment by andymc12** [comment]
@scottmarlow assuming Santiago agrees, would it be possible to put this in the current EE stream as a micro release? i.e. 9.0.1? I think it's good for vendors to pass this test for EE 9 once it is corrected.

**Comment by spericas** [comment]
@scottmarlow @andymc12 The proposed change makes sense to me. Not sure about the history of this and why it was not flagged before. Would like get @jansupol's opinion as well.

**Comment by scottmarlow** [comment]
> @scottmarlow assuming Santiago agrees, would it be possible to put this in the current EE stream as a micro release? i.e. 9.0.1? I think it's good for vendors to pass this test for EE 9 once it is corrected.

Currently we do not update any tests for an already shipped EE release, as that would invalidate all of the various EE SPEC API implementations that have already gone through the SPEC Ballot process.  More simply, making a test change that technically is correct, may cause other implementations that did what the current TCK test expected, might see failures.  The only way historically to avoid that problem is to only exclude tests for accepted challenges.

**Comment by scottmarlow** [comment]
> @scottmarlow it's basically a "pre-challenge". We are seeing this as a failure when running the RESTful WS 3.0 TCK (CTS?) with Open Liberty using RESTEasy+Weld. @brideck or I will most likely be opening an official challenge, but since it was a fairly easy fix, I thought I would start with it here. Thanks!

Please do note that the official TCK challenge issue should be created in the github.com/eclipse-ee4j/jaxrs-api/issues and reference this issue.  I'm adding a issue template here to hopeful help explain this better. :-)

**Comment by andymc12** [comment]
Sounds good - thanks @scottmarlow and @spericas!

**Comment by jansupol** [comment]
I think this change is ok. The purpose of the test was to check the registered `ExceptionMapper` would be working and retrievable using `Providers.getExceptionMapper`. The returned proxy is fine.

**Comment by edbratt** [comment]
A question on point of order here seems appropriate -- Shouldn't this have been filed with the Jakarta REST team first? If the component committers believe this is in error -- then the platform simply incorporates the change. Filing this first at the Platform seems the wrong way to go for issues like this.

**Comment by andymc12** [comment]
@edbratt Is the TCK challenge process documented somewhere?  I don't disagree with you on the expected order, but multiple committers form the Jakarta REST team did review and approve the change to the TCK including the project lead, so I don't think anything was done improperly, but I'll plan to file challenges in the Jakarta REST project first moving forward.

**Comment by scottmarlow** [comment]
> A question on point of order here seems appropriate -- Shouldn't this have been filed with the Jakarta REST team first? 

@edbratt is your question directed at TCK challenges specifically?  

For TCK challenges, we have been requesting those to be created in the respective SPEC project (e.g. Jakarta REST would be where I expect the related challenge to be created).  

From an ordering perspective, I agree that TCK challenges should be created in the respective SPEC project, however, I considered this issue as representing the upstream (e.g. master branch currently) change to be made (as per Jakarta REST SPEC lead input from Santiago Pericas-Geertsen).  Whether an actual TCK challenge is created or not, it seemed okay to accept this change, instead of redirecting it.

Still, if there are advantages to creating issues like this in the relevant SPEC project so that the SPEC projects can be directly responsible for the change, that could be interesting also (since we do want to head in that direction).
