### ISSUE TITLE
2 standalone JSP tests failing 

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#624]
**Describe the bug**
Two JSP standalone tests failing 

com/sun/ts/tests/jsp/spec/el/jsp/URLClient.java#eLDeferredValueCoercionTest
com/sun/ts/tests/jsp/spec/el/language/URLClient.java#rValueCoercion2Test

[jsplogs.txt](https://github.com/eclipse-ee4j/jakartaee-tck/files/6047781/jsplogs.txt)

complete test run logs at https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1243/nodes/74/steps/295/log/?start=0

**To Reproduce**
Download https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-pages-tck-3.0.0.zip
Run JSP standalone tck in JDK11 .
docker/jsptck.sh has the tck run scripts

**Comment by arjantijms** [comment]
Reproduced here in JSP/Pages project: https://ci.eclipse.org/jsp/job/2_jsp-run-tck-against-staged-build/37/artifact/pages-tck/bin/summary.txt

**Comment by smillidge** [comment]
Servlet project I would think as GlassFish just pulls in implementations from there.

**Comment by scottmarlow** [comment]
> Servlet project I would think as GlassFish just pulls in implementations from there.

Do you agree @markt-asf that the JSP (Servlet?) team could help with this failure that has been recreated in https://ci.eclipse.org/jsp/job/2_jsp-run-tck-against-staged-build/37/artifact/pages-tck/bin/summary.txt?  If yes, we can create a JSP/Servlet issue and link to it from here.

FYI, link to [test source with description is here](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jsp/spec/el/jsp/URLClient.java#L95).

**Comment by scottmarlow** [comment]
Do the two JSP tests that fail with Standalone JSP TCK also fail with the Platform TCK?

**Comment by markt-asf** [comment]
This isn't an issue for the Servlet project for 2 reasons. First, the Servlet project only provides an API and does not provide an implementation. Second, the failures are in the Pages TCK, not the Servlet TCK.

This might be an issue for the WaSP project (the Pages implementation was moved out of the Pages project in late 2020) however, I see the same TCK failures with JDK 11 and Tomcat 10. Given that Tomcat 10 has previously passed the Pages TCK with Java 11 I strongly suspect that the root cause is a change to the Pages TCK. Assuming the CI runs can tell you which commit (or range of commits) introduced the failure, which commit was it?

**Comment by markt-asf** [comment]
The problem is that the WAR file that supports these tests is missing a class. This appears to be a long standing bug in the JSP TCK. If the EL TCK is built before the JSP TCK (and the compiled classes are not cleaned up between builds) the the JSP TCK will be built correctly. A clean build of the TCK, however, will be missing the required class. I should have a PR for this shortly.

**Comment by scottmarlow** [comment]
Started build + test of Standalone JSP TCK via https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-standalonetck-build-run-910/28/

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1279/testReport/com.sun.ts.tests.jsp.spec.el.jsp/URLClient/standalone_tck_run___jsp___eLDeferredValueCoercionTest + https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1279/testReport/com.sun.ts.tests.jsp.spec.el.language/URLClient/standalone_tck_run___jsp___rValueCoercion2Test are now passing!  

Thanks for fixing this issue @markt-asf!  Very much appreciated!
