### ISSUE TITLE
Correct JAXRS references in SAAJ TCK userguide

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#65]
[config.inc](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/user_guides/saaj/src/main/jbake/content/config.inc) + [rebuild.inc](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/user_guides/saaj/src/main/jbake/content/rebuild.inc) + [_config.yml](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/user_guides/saaj/src/main/jbake/assets/_config.yml) refer to jaxrs.

I'm not sure of what the content should be exactly, but jaxrs settings probably don't belong in the SAAJ userguide.  For example:

> Set the `jaxrs_impl_name` property to the name of the
  {TechnologyShortName}

**Comment by scottmarlow** [comment]
I also found JAXRS references in other userguides as well (beyond the JAX-RS TCK userguide), [a list is here.](https://paste.fedoraproject.org/paste/rhGCSYsrfgBCVm~~tozzuw)

**Comment by bshannon** [comment]
Yes, the JAX-RS references are examples from the template and should be removed from
the other user guides.  The rebuild.inc is also an example, but it's only included if you set
the `rebuild` attribute in attributes.conf.  Since this isn't being pushed to a web site, much of
the _config.yml content doesn't really matter and so wasn't updated.
