### ISSUE TITLE
Signature tests for javax.rmi package

### ISSUE THREAD

**Issue by dblevins** [eclipse-ee4j/jakartaee-tck#652]
Per the vote on the Jakarta Enterprise Beans list we opted not to remove calls to `PortableRemoteObject.narrow`.  These will be left in the API and we now need signature tests for the `javax.rmi` package to be added as this API (and related signature tests) have been removed from Java SE 11.

Vote results:  https://www.eclipse.org/lists/ejb-dev/msg00207.html

**Comment by dblevins** [comment]
As noted in the Jakarta EE TCK dev list, we have three optional groups in Jakarta Enterprise Beans:

 - Embeddable Enterprise Beans Container

 - Enterprise Beans 2.x API
      Session Beans
      2.x Local and Remote Home and Component views
      TimedObject interface
      SessionSynchronization interface

 - Entity Beans
      2.x / 1.x CMP/BMP Entity Beans
      Enterprise Beans QL

These new signature tests should be bound to the `ejb_2x_optional` group, not any corba-related optional groups.

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/orb/blob/master/omgapi/src/main/java/javax/rmi/PortableRemoteObject.java seems to be built as [org.glassfish.corba:glassfish-corba:4.2.3](https://repo1.maven.org/maven2/org/glassfish/corba/glassfish-corba-omgapi/4.2.3/glassfish-corba-omgapi-4.2.3.jar)

**Comment by dblevins** [comment]
@scottmarlow how is that related to needing signature tests?

**Comment by dblevins** [comment]
For those interested, here's where that class can be found on the Apache side: https://github.com/apache/geronimo-yoko/blob/master/yoko-rmi-spec/src/main/java/javax/rmi/PortableRemoteObject.java

**Comment by scottmarlow** [comment]
> @scottmarlow how is that related to needing signature tests?

It may be helpful when we look at generating the javax.rmi.PortableRemoteObject signature map file.

**Comment by gurunrao** [comment]
@dblevins - Please confirm on jar and package for which signature needs to be generated.
Should we use `Maven GAV glassfish-corba-orb:glassfish-corba-orb:4.2.3` and package `javax.rmi` ?

**Comment by scottmarlow** [comment]
I removed myself from this issue to encourage others to work on it.  If no one else does it, I will work on it after finishing other tasks.

**Comment by dblevins** [comment]
@gurunrao I can't confirm that dep has signatures identical to the `javax.rmi` package in JDK 8, only that "it should".  In JDK 8 the `javax.rmi` package is found in `jdk1.8.0_151.jdk/Contents/Home/jre/lib/rt.jar`.  If we can use a JDK 8 install to generate the signatures, that'd probably be best.

In terms of package, yes `javax.rmi` is correct.

**Comment by gurunrao** [comment]
@dblevins 
Signature tests fails, when signature is generated from rt.jar, changes for Sigtest with rt.jar - https://github.com/eclipse-ee4j/jakartaee-tck/compare/master...gurunrao:sigtest-rmi

CI run https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaee-tck-guru/job/sigtest-rmi/2/testReport/junit/com.sun.ts.tests.signaturetest.javaee/JavaEESigTest/signatureTest_from_servlet/

```
Failure message:

----------------------------------
Added Annotations
-----------------

javax.rmi.PortableRemoteObject:         finalize():anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="9")

--------------------------------
```

Signature tests PASS when signature is generated from glassfish-corba-orb.jar, changes for Sigtest with glassfish-corba-orb.jar - https://github.com/eclipse-ee4j/jakartaee-tck/compare/master...gurunrao:sigtest-rmi-remove-deprecated?expand=1

CI run passes with glassfish-corba-orb.jar generated signature file, CI run https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaee-tck-guru/job/sigtest-rmi-remove-deprecated/2/testReport/



We are currently using version of javax.rmi package as 1.8, please suggest alternate version.
Also Platform TCK framework allows to ignore optional packages during signature tests(https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jakartaee/bin/ts.jte.jdk11#L1393), shall we add package javax.rmi in ts.jte.jdk11 to be ignored by default?

**Comment by gurunrao** [comment]
@dblevins  

Based on changes mentioned in comment https://github.com/eclipse-ee4j/jakartaee-tck/issues/652#issuecomment-814173727, We have following query:

- We are seeing failures post generation of signature files from JDK 8 `rt.jar`, shall we proceed with  `glassfish-corba-orb.jar`?
- what is version of package `javax.rmi`, which needs to be added in signature map files?
- Shall we add `javax.rmi` at line https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jakartaee/bin/ts.jte.jdk11#L1393, since 'javax.rmi' is optional package and can be ignored by default?
- Also we need to ignore `javax.rmi` during JDK 8 run, hence we will add `javax.rmi` at https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jakartaee/bin/ts.jte#L1407


CC @scottmarlow

**Comment by scottmarlow** [comment]
> @dblevins
> Signature tests fails, when signature is generated from rt.jar, changes for Sigtest with rt.jar - [master...gurunrao:sigtest-rmi](https://github.com/eclipse-ee4j/jakartaee-tck/compare/master...gurunrao:sigtest-rmi)
> 
> CI run https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaee-tck-guru/job/sigtest-rmi/2/testReport/junit/com.sun.ts.tests.signaturetest.javaee/JavaEESigTest/signatureTest_from_servlet/
> 
> ```
> Failure message:
> 
> ----------------------------------
> Added Annotations
> -----------------
> 
> javax.rmi.PortableRemoteObject:         finalize():anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="9")
> 
> --------------------------------
> ```
> 
> Signature tests PASS when signature is generated from glassfish-corba-orb.jar, changes for Sigtest with glassfish-corba-orb.jar - https://github.com/eclipse-ee4j/jakartaee-tck/compare/master...gurunrao:sigtest-rmi-remove-deprecated?expand=1
> 
> CI run passes with glassfish-corba-orb.jar generated signature file, CI run https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaee-tck-guru/job/sigtest-rmi-remove-deprecated/2/testReport/
> 
> We are currently using version of javax.rmi package as 1.8, please suggest alternate version.
> Also Platform TCK framework allows to ignore optional packages during signature tests(https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jakartaee/bin/ts.jte.jdk11#L1393), shall we add package javax.rmi in ts.jte.jdk11 to be ignored by default?
> CC @scottmarlow

If we solve https://github.com/eclipse-ee4j/jakartaee-tck/issues/156 (which I am still working on), the failure that you mentioned will be solved (in that we can use JDK 8 signatures for greater than JDK 8 use).  Otherwise, we need to use the JDK 11 equivalent javax.rmi package to generate our JDK11 signatures.

**Comment by gurunrao** [comment]
@scottmarlow - Thanks for clarity on jars, we will proceed with glassfish-corba-orb.jar for signature generation.

If have clarity on below items, We can go ahead and raise PR:
- what is the version of package javax.rmi, which needs to be added in signature map files?(sample map version for servlet can be referred here https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jakartaee/bin/sig-test_se11.map#L108)
- Shall we add javax.rmi at line https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jakartaee/bin/ts.jte.jdk11#L1393, since 'javax.rmi' is optional package and can be ignored by default?

**Comment by gurunrao** [comment]
PR for the issue - https://github.com/eclipse-ee4j/jakartaee-tck/pull/713
