### ISSUE TITLE
Update the Jakarta EE Platform TCK user guide to require implementations supporting Jakarta XML Binding to pass the Jakarta XML Binding TCK on JDK11

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#678]
In addition to passing the DI, CDI, BV TCKS, Jakarta EE Platform implementations that support XML Binding and claiming their implementation is EE 9.1 compatible on JDK11 must also pass the [Jakarta XML Binding](https://jakarta.ee/specifications/xml-binding/3.0) TCK on JDK11.  

This issue is for updating the Jakarta EE Platform User Guide to state this requirement.

CC @edbratt

**Comment by edbratt** [comment]
I believe this is actually a requirement for products supporting Jakarta EE 9 and supporting XML Binding -- for either JDK 8 or JDK 9 because the Spec. requires jakarta.xml.bind* while JDK8 only provides javax.xml.bind. Regardless, I will propose text changes to satisfy this issue in https://github.com/eclipse-ee4j/jakartaee-tck/pull/702

**Comment by scottmarlow** [comment]
resolved via https://github.com/eclipse-ee4j/jakartaee-tck/pull/702/files#diff-3e34a09d1f65d663a5b839245b5dd6bdd76aae290795d9343a7f911eb5fb3b92R102
