### ISSUE TITLE
Revert, back out, or properly fix this expiry date Servlet TCK commit

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-tck#95]
Per the discussion on the [TCK mailing list](https://www.eclipse.org/lists/jakartaee-tck-dev/msg00202.html), there were some errant changes made to the Servlet TCK.  These changes are preventing some app servers from certifying to Jakarta EE 8.  These changes need to be reverted, backed out, or properly fixed.

https://github.com/eclipse-ee4j/jakartaee-tck/commit/5d63739aa87016a4bb35516039ac7e83b30298a9#diff-fe27b4530bdef6baa5447c990d9f786f

**Comment by bshannon** [comment]
@markt-asf Mark, I'm hoping you'll submit a PR to undo this change.

**Comment by markt-asf** [comment]
My preference is to figure out why the fix isn't working as expected and correct it. Looks like the original report has some useful info on that. I'll take a look.

**Comment by markt-asf** [comment]
This bug report is invalid. The modified TCK test is correct. The test is failing because the server isn't following the [cookie V0 specification](https://curl.haxx.se/rfc/cookie_spec.html). The changes in 5d63739 have exposed a configuration issue in the server under test.

The root cause is that the server that is current is currently failing the TCK is issuing Set-Cookie headers with expires attributes that use 2 digit years. 
`[javatest.batch] 07-08-2019 09:21:40: ÂTRACE: [WIRE] - << "Set-Cookie: name1=value1; Expires=Mon, 08-Jul-19 13:21:42 GMT[\r][\n]"`

Jakarta Commons HTTP client 3.1 uses "[EEE, dd-MMM-yyyy HH:mm:ss z](https://svn.apache.org/viewvc/httpcomponents/oac.hc3x/tags/HTTPCLIENT_3_1/src/java/org/apache/commons/httpclient/cookie/NetscapeDraftSpec.java?view=annotate#l187)" to process expires headers. When the expires header provided by the server is parsed using that format the result is:
`0019-07-08 13:21:42 GMT`
The two digit year is read as 19 AD rather than the intended 2019AD

I have put together a [standalone Java app](https://github.com/markt-asf/tomcat-bugs/blob/master/src/java/org/apache/tomcat/tck/servlet/CookieDates.java) that demonstrates all of this.

The [original report](https://www.eclipse.org/lists/jakartaee-tck-dev/msg00202.html) stated that

>  Our server, by default, uses the latest RFC-compliant date format, but HttpClient did not like it so we had to configure it to use the Netscape cookie expiry format.

It looks like a configuration error was made. If the configuration is corrected to use 4 digit years as per the V0 cookie spec, the test should pass.

**Comment by alwin-joseph** [comment]
@markt-asf Thanks for taking a look. Can you please reply to the mail thread at jakartaee-tck-dev@eclipse.org (and to Hank Ibell who raised the issue). We could keep the discussion in the forum so they can also reply.

**Comment by kwsutter** [comment]
@markt-asf Your analysis may be correct, but that still does not allow us to modify the tests before Jakarta EE 8 is released.  Everything that was certified to Java EE 8 has to be able to certify against Jakarta EE 8 with no coding changes.  Modifying testcases that affect this ability is not allowed at this time.  Sorry, but we have to live with this rule for Jakarta EE 8.  Thanks.

**Comment by markt-asf** [comment]
Then I'd suggest adding the test to the exclusion list for the Jakarta EE 8 TCK else you'll have spec compliant Servlet containers (like Tomcat) unable to pass the TCK. The test can then be removed from the exclusion list as soon as the Jakarta EE 8 TCK is released and work starts on the next release.

**Comment by kwsutter** [comment]
If that's the proper path to take to resolve this situation, then I'm okay.  But, I think the change should actually be backed out since our priority should be existing Java EE 8 compliant application servers.  @bshannon What's your take?

**Comment by bshannon** [comment]
Back out the fix.

If you're required to run the test in the en_US locale, that's acceptable per the TCK rules.

If a compliant server running in the en_US locale still fails to pass the test, they can file
a test challenge and we can exclude the test if the challenge is accepted.

Since we decided to not allow for "alternate" tests in Jakarta EE, the fix would need to be
applied after Jakarta EE 8 for a future release of the Servlet spec.

**Comment by alwin-joseph** [comment]
@markt-asf We will need to start building latest bundles to promote and release, after this is resolved.

**Comment by kwsutter** [comment]
Just wondering the current state of this issue?  Was this change backed out?  If so, what was the PR?  thanks.

**Comment by alwin-joseph** [comment]
Yes the changes were backed out : https://github.com/eclipse-ee4j/jakartaee-tck/pull/99

**Comment by kwsutter** [comment]
Resolved via PR #99.  Thanks, @alwin-joseph, for the pointer!
